### PR TITLE
Fix ffmpeg 7 compatibility

### PR DESCRIPTION
**Pull request by MarianoFacundoArch**

### CODE REVIEW

**Comment by Azarattum** [comment]
Would it break with the older versions after this PR or would it support both?

**Comment by MarianoFacundoArch** [comment]
My code works on both

**Comment by totallytavi** [comment]
Made a patch for this. You can download and use it by placing it in a folder called "patches" in your project and running `npx patch-package`
[fluent-ffmpeg+2.1.2.patch](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/files/15287681/fluent-ffmpeg%2B2.1.2.patch)

**Comment by njoyard** [comment]
@MarianoFacundoArch can you please revert style changes in `lib/capabilities.js`? I'll merge it after that.

**Review by renmu123 — APPROVED** [review]

**Comment by govindrai** [comment]
@MarianoFacundoArch could you revert the style changes please? It makes the PR very difficult to review and folks could use this update. 

Fwiw, I tried downloading your package fluent-ffmpeg-7 and ran into the same issues.

**Comment by totallytavi** [comment]
@govindrai If you want a fix now, try the patch file I attached above.

**Comment by totallytavi** [comment]
@njoyard Opened #1274

**Comment by njoyard** [comment]
Replaced by #1274

**Pull request closed without merging**
