### PR TITLE
Missing capability method getAvailableEncoders

### PR DESCRIPTION
**Pull request by rhodgkins**
Add both `getAvailableEncoders` and `availableEncoders`.

### CODE REVIEW

**Comment by rhodgkins** [comment]
Not sure why the build is failing - its happening on the other 2 pull requests occasionally too 😔

**Comment by njoyard** [comment]
Yeah, that's due to some timing-dependent tests that I wasn't able to rewrite correctly.
I have invited you to the team, hopefully that enables you to relaunch PR test jobs on jenkins.

**Comment by rhodgkins** [comment]
👍 done!

Any chance when merging this in that you could also push a new version to npm?

**Comment by njoyard** [comment]
Yep. Do you have an account on npmjs.org ?

**Comment by rhodgkins** [comment]
Yep - rhodgkins

**Comment by njoyard** [comment]
Okay, added you on npmjs so that you can push the new version if you want to. I won't be able to do it myself for a few days.

**Pull request merged**
