### PR TITLE
ffprobe - parsing of chapters metadata

### PR DESCRIPTION
**Pull request by bartolomeon**

### CODE REVIEW

**Comment by njoyard** [comment]
Thanks, it would be nice if you could update the README by adding an example of how chapters look like.

**Comment by njoyard** [comment]
Merged in 0d635e6ef8a2d474e2783237a13a58e41e4fe61d

**Comment by briancampo** [comment]
Still getting empty chapters array.  It seems like a flag on the ffprobe spawn call is missing -
```
 // Spawn ffprobe
 var src = input.isStream ? 'pipe:0' : input.source;
 var ffprobe = spawn(path, ['-show_streams', '-show_format', '-show_chapters'].concat(options, src)); // this line would change in master
```
Adding the previous to the current master works for me.  I can put a new issue and merge request together for this but wasn't sure if that was the best way.

**Comment by bartolomeon** [comment]
This may be related to changes within the ffmpeg itself. My changes were aimed to work with v3.0 and it does work on production since then in one of my projects. You may check when this flag was introduced first.

**Pull request closed without merging**
