### PR TITLE
Adding support for ffprobe on streams as suggested in #365

### PR DESCRIPTION
**Pull request by timdp**
Credit to @acidhax for describing this fix. I only turned it into a PR.

@njoyard originally wrote the if that throws on streams. Is there a reason why we shouldn't use ffprobe on streams? Just checking.

### CODE REVIEW

**Comment by njoyard** [comment]
Thanks for those @acidhax and @timdp.
Can you please add some tests for this? No need to test every corner of ffprobe, just ensure that it works well on 1 or 2 streams and handles errors correctly.

**Comment by timdp** [comment]
Sure, I'll get right on that. Just wanted to check that the scenario makes sense first. Thanks for the quick response!

**Comment by njoyard** [comment]
Oh, I kind of bypassed your question.

The reason for the lack of stream support is just that I didn't *think* it worked. Plus in my opinion it didn't make any sense because ffprobe-ing a stream *consumes* data from it, which is not really what you want most of the time.

Before merging, we'll have to ensure that calls to ffprobe are skipped when running a command on a stream.

**Comment by timdp** [comment]
Yeah, it works pretty well. I already had code for it without fluent-ffmpeg, but I figured I might as well port it.

I assume that by your second paragraph, you mean that people won't be able to run any additional ffmpeg logic on the stream once ffprobe has analyzed it? I didn't expect it to be any different because I view `ffmpeg.ffprobe()` as shorthand for spawning a process that reads from stdin, but I guess it could confuse people, yes. Then again, I imagine that people who understand how streams work will be able to figure out which workflow makes sense. But it would of course be better if the API prevented weird stuff from happening.

What do you mean by "calls to ffprobe are skipped"? Could you provide an example of user code that would trigger this skipping behavior?

**Comment by timdp** [comment]
I suppose that if you wanted to run `ffmpeg` and `ffprobe` on the same input stream, you could create a passthrough. Perhaps that should be an option you can pass to both functions? 

However, to me, that feels like duplicating existing behavior found in Node's streams and burying it inside fluent-ffmpeg's code. If the user already has the stream, they might as well handle the passthrough stuff themselves.

Regardless, that sort of feature seems like something for another branch.

**Comment by acidhax** [comment]
Glad it helped!

**Comment by njoyard** [comment]
No, there is a problem when you're using any stream that does not contain live data.

Imagine a stream that, in the end, provides the content of a video file (perhaps from a hosting service or whatever). ffprobe will consume the start of the stream to read the file header and generate its output. Later on, when ffmpeg starts processing the stream, the header data is no longer available and it won't be able to determine the input format, codecs and so on. Worse, most popular formats nowadays put their "header" at the *end* of files. Thus ffprobe would have to consume the stream *until the end* and there wouldn't be a single byte left available for ffmpeg.

Using a PassThrough stream won't help at all. What you need is some kind of duplication device: a module that takes one readable stream as an input and produces two readable streams as an output, both with identical data. Of course, if the data is consumed on one side, such a module would need to cache the data *in memory* to keep it available for the other stream, which could cause memory usage issues...

As we're not able to determine in advance whether a stream is live data or is just an interface to access the contents of a (perhaps remote) file, we have to make the most conservative choice and *not* read anything from it as long as we're expected to run ffmpeg on that stream later on. That is, only run ffprobe on a stream when *explicitly* asked by the user, and never automatically (for example `.screenshots()` runs ffprobe before ffmpeg in some cases).

**Comment by njoyard** [comment]
And I completely agree that we should not handle stream-level issues in fluent-ffmpeg. If the user needs a stream duplicated, it's her problem.

**Comment by acidhax** [comment]
In my usage, the stream was disposable.

**Comment by njoyard** [comment]
Yup, disposable but not reusable. You could generate the same stream again by some means (eg. `fs.createReadStream()`) but given a single stream, consumed data was only available once.

**Comment by timdp** [comment]
> Imagine a stream that, in the end, provides the content of a video file (perhaps from a hosting service or whatever). ffprobe will consume the start of the stream to read the file header and generate its output. Later on, when ffmpeg starts processing the stream, the header data is no longer available and it won't be able to determine the input format, codecs and so on.

Yeah, but I still think that people who understand streams will assume that this is the intended behavior. Without going into too much detail, personally, I'm streaming files from Amazon S3 and analyzing them on the fly. When I subsequently transcode the file, I just stream it again. That second step does listen for the `codecData` event as well. While I'm not actually using the data at this point, the returned object does contain the most useful information, so it could theoretically be used as a substitute for ffprobe. It would of course be even better if it were identical to the probe output.

> Worse, most popular formats nowadays put their "header" at the end of files. Thus ffprobe would have to consume the stream until the end and there wouldn't be a single byte left available for ffmpeg.

Yeah, I wasn't entirely sure if that happened for videos as well; I've only seen it happen with MP3s. It's significantly going to slow down the ffprobe call, of course. I'm not familiar enough with Node streams to know if they would allow this:

a) Pass the length of the stream (i.e., the size of the input file(s)) to the consumer (i.e., ffprobe).
b) As soon as the consumer knows where the metadata are, fast-forward the stream to that point. In the case of S3, that would effectively make it perform an HTTP Range request.

If I had to guess, I would say that streams aren't advanced enough and they'd just download the entire file and drop most of the data. If so, in my case, both fluent-ffmpeg and the AWS SDK would have to start supporting a more advanced streaming API, which isn't very likely.

> Using a PassThrough stream won't help at all. What you need is some kind of duplication device: a module that takes one readable stream as an input and produces two readable streams as an output, both with identical data. Of course, if the data is consumed on one side, such a module would need to cache the data in memory to keep it available for the other stream, which could cause memory usage issues...

Yeah, I got confused about how `PassThrough` works. There are tons of npm packages that handle streaming so there's probably one that demuxes a binary stream. Memory usage could certainly be an issue, but then I think it becomes the demuxer's responsibility to implement a swapping mechanism or something.

> As we're not able to determine in advance whether a stream is live data or is just an interface to access the contents of a (perhaps remote) file, we have to make the most conservative choice and not read anything from it as long as we're expected to run ffmpeg on that stream later on. That is, only run ffprobe on a stream when explicitly asked by the user, and never automatically (for example .screenshots() runs ffprobe before ffmpeg in some cases).

I totally agree, but it sounds like `screenshots()`—which I haven't used, so I could be wrong—is a pretty advanced function that deviates from what I assumed was the core responsibility of fluent-ffmpeg: to provide a nicer API to manage ffmpeg invocations, without adding too much complex logic on top. Once you start doing the latter, it sounds to me like that logic should be in a separate module that depends on fluent-ffmpeg, and that module should sort out the streaming issue, perhaps simply by not supporting streams flat out. Just my two cents.

**Comment by timdp** [comment]
I've noticed that with this patch, transcoding streams can cause random `EPIPE` errors. The underlying reason seems to be that ffprobe gets run underneath, which triggers the issue outlined by @njoyard: ffprobe probably consumes part of the stream.

But why does `processor.js` need to run ffprobe when I ask it to transcode? ffmpeg outputs codec data by default and that's why I listen for the `codecData` event (which is broken with streams but there's a PR).

I've also noticed that `processor.js` holds off on running ffprobe until the first `progress` listener gets added. Doesn't this mean that we'll miss data too?

**Comment by njoyard** [comment]
@timdp sorry for the delay.

I'm not the one who wrote the original version of this code, but basically, we ffprobe the input to get codec data and dimensions. This is not always necessary (it is when resizing for example) and maybe the logic here could be improved. But it boils down to using something a bit more reliable than ffmpeg standard output, which is not part of its spec. That's also why I added capability checks before transcoding (because it's much easier to do this way than running ffmpeg and hoping to be able to parse the error message it produces).

**Comment by njoyard** [comment]
About your previous message, overall I think (again) that the logic of calling ffprobe could be reworked. And I agree stream issues should be known by the user, but basically when they ask for a transcode, they should not get errors due to the actual implementation of the lib they used.

IOW, if we (as fluent-ffmpeg authors) decide to call ffprobe, the implementation should cope with any output and not mess up the stream. OTOH, if the user manually calls ffprobe on their stream, and then try to transcode it, they ought to know the caveats.

**Comment by timdp** [comment]
Thanks for the elaborate response. No worries about the slight delay.

Given that the ffprobe logic is rather deeply entrenched in fluent-ffmpeg, perhaps a separate fluent-ffprobe would make more sense? ffprobe doesn't have as many options as ffmpeg, of course, but a cleaner API still wouldn't hurt.

**Comment by njoyard** [comment]
That's an idea. There's a node-ffprobe module on npm/github. I contributed to it a few years(?) ago. Maybe we could remove ffprobe support altogether, but that would break compatibility (some people already use Ffmpeg.ffprobe()). Or just redirect Ffmpeg.ffprobe to node-ffprobe. I'm not sure what the best solution is. I'll think about it, but don't refrain from proposing changes as pull requests !

**Comment by timdp** [comment]
Yeah, I came across that module too. The interface is far less advanced than fluent-ffmpeg's though, so there's room for improvement. That being said, the solution I cobbled together using only `child_process` isn't too crazy either.

**Comment by njoyard** [comment]
Thanks!
We will need to update the documentation, though. If you have time, add it to this pull request; otherwise I'll do it when I have some time.

**Comment by chazmo03** [comment]
I added #451 on top of this to handle some of the issues I had when trying to run this code. I am trying to stream directly from S3 and pipe into ffprobe. I would like to second the notion that any user using ffprobe with streams should realize that it's a one-time affair. If that means that you can't do screenshots from a stream because it needs to read the stream twice, then that's where the error/warning should go. It seems like ffprobe can totally handle streams (and already pretty much does). My improvements mainly ensure that the input stream gets paused once ffprobe exits.

**Comment by njoyard** [comment]
Merged in 9380132

**Pull request closed without merging**
