### PR TITLE
Fixing Bug resolve "./lib-cov/fluent-ffmpeg"

### PR DESCRIPTION
**Pull request by flibustier**
In order to fix bug referenced in Issues #139, #358 and #573

Using only one require to avoid all bug related to Webpack, meteor, …

### CODE REVIEW

**Comment by flibustier** [comment]
Good news ! :) I created a PR #946 to fix CI first !

**Comment by JonathanBuchner** [comment]
The above pr fixed the issues for me as I manually changed my developer environment.  I have been asked to remove fluent-ffmpeg from our app because of this error.  Thanks for all the hard work that goes into fluent-ffmpeg, but this is a breaking enough bug that a different method will be used unless this pr is add or similar fix is added.  Thanks!

**Comment by flibustier** [comment]
@njoyard is-it possible to merge this ? :)

**Comment by olingern** [comment]
I'm not sure this PR totally fixes the problem @njoyard mentioned [here](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/573#issuecomment-238790339)

> It parses source files and tries to include everything that is in a require() call, even if it's conditional. Nothing fluent-ffmpeg can do here.

Does [this](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/573#issuecomment-305408048) other comment not fix the issue?

```javascript
plugins: [
    new webpack.DefinePlugin({
        'process.env.FLUENTFFMPEG_COV': false
    })
]
```

**Comment by flibustier** [comment]
> I'm not sure this PR totally fixes the problem @njoyard mentioned [here](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/573#issuecomment-238790339)

I'm not sure for meteor behavior but for Webpack this is clear fix!

> Does [this](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/573#issuecomment-305408048) other comment not fix the issue?
> 
> ```js
> plugins: [
>     new webpack.DefinePlugin({
>         'process.env.FLUENTFFMPEG_COV': false
>     })
> ]
> ```

But it’s not at the application or project using a dependency, to fix problems related to this dependency, imagine if all project need a manual fix for each dependency…
And the fix in this PR is pretty simple and works well!

**Comment by joebernard** [comment]
Will there be a version bump associated with this patch? Looks like the project is still on version 2.1.2 from 2017.

**Comment by Silverreaper07** [comment]
> In order to fix bug referenced in Issues #139, #358 and #573
> 
> Using only one require to avoid all bug related to Webpack, meteor, …

Mind telling me where to put the `require `  and what should I require.I am using npm and create-react-app.
Or is there any other workaround?

**Comment by flibustier** [comment]
Hello @Silverreaper07, you can manually change the `require` in your project directory : `node_modules/fluent-ffmpeg/index.js` 
Hope it helps you !

**Pull request merged**
